return {
	Level = 1,
	Experience = 0,
	Inventory = {
		Items = {},
		Gold = 0,
	},
	Skills = {},
	Stats = {
		Attack = {
			Level = 1,
			Experience = 0,
		},
		Defence = {
			Level = 1,
			Experience = 0,
		},
		Strength = {
			Level = 1,
			Experience = 0,
		},
		Hitpoints = {
			Level = 5,
			Experience = 0,
		},
		Ranged = {
			Level = 1,
			Experience = 0,
		},
		Magic = {
			Level = 1,
			Experience = 0,
		},
		Blacksmithing = {
			Level = 1,
			Experience = 0,
		},
		Cooking = {
			Level = 1,
			Experience = 0,
		},
	},
	Quests = {},
	Location = {
		Map = "StartingTown",
		X = 0,
		Y = 0,
	},
	TimePlayed = 0,
}
